# Conservative defaults. Tune per project.
avoid-breaking-exported-api = false
cognitive-complexity-threshold = 25
too-many-arguments-threshold = 8
type-complexity-threshold = 250
single-char-binding-names-threshold = 5
